<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>FSA List Report</title>
    <style>
        @page {
            margin: 15mm;
            size: A4 portrait;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h1 {
            margin: 0;
            font-size: 16px;
            color: #333;
        }

        .header p {
            margin: 3px 0;
            font-size: 11px;
            color: #666;
        }

        .info-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }

        .info-table td {
            padding: 5px;
            font-size: 11px;
            border: 1px solid #ddd;
        }

        .info-table td.label {
            font-weight: bold;
            background-color: #f5f5f5;
            width: 100px;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        .report-table th {
            background-color: #4CAF50;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #333;
            font-size: 11px;
        }

        .report-table td {
            padding: 6px 8px;
            text-align: left;
            border: 1px solid #ddd;
            font-size: 11px;
        }

        .report-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9px;
            color: #999;
            border-top: 1px solid #ddd;
            padding: 5px 0;
        }

        .page-break {
            page-break-before: always;
        }

        .total-count {
            margin-top: 15px;
            font-weight: bold;
            text-align: right;
            font-size: 12px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>FSA List Report</h1>
        <p><strong>Surelife Care & Services</strong></p>
    </div>

    <table class="info-table">
        <tr>
            <td class="label">Branch:</td>
            <td>{{ $branch->BranchName ?? 'N/A' }}</td>
            <td class="label">Date Generated:</td>
            <td>{{ now()->format('M d, Y h:i A') }}</td>
        </tr>
        <tr>
            <td class="label">MCPR Period:</td>
            <td>{{ $mcprData->year ?? 'N/A' }} ({{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }})
            </td>
            <td class="label">Total Records:</td>
            <td>{{ count($reportData) }}</td>
        </tr>
    </table>

    @if(count($reportData) > 0)
        <table class="report-table">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 35%;">Name</th>
                    <th style="width: 20%;">Position</th>
                    <th style="width: 20%;">Date Accomplished</th>
                    <th style="width: 20%;">Mobile Number</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportData as $index => $staff)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $staff['name'] }}</td>
                        <td>{{ $staff['position'] }}</td>
                        <td>{{ $staff['dateAccomplished'] }}</td>
                        <td>{{ $staff['mobileNumber'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="total-count">
            Total Staff Members: {{ count($reportData) }}
        </div>
    @else
        <div style="text-align: center; padding: 20px; font-style: italic; color: #666;">
            No active staff found for this branch.
        </div>
    @endif

    <div class="footer">
        Generated by Surelife Admin Panel on {{ now()->format('M d, Y h:i A') }}
    </div>
</body>

</html>