/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  safelist: [
    'bg-white',
    'rounded-xl',
    'shadow-lg',
    'overflow-hidden',
    'mb-6',
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-gray-50',
    'to-gray-100',
    'px-6',
    'py-4',
    'py-6',
    'p-6',
    'border-b',
    'border-gray-200',
    'text-lg',
    'font-bold',
    'text-gray-800',
    'flex',
    'items-center',
    'w-5',
    'h-5',
    'mr-2',
    'text-indigo-600',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'gap-4',
    // Gradient from colors
    'from-indigo-50',
    'from-blue-50',
    'from-emerald-50',
    'from-purple-50',
    'from-amber-50',
    'from-red-50',
    'from-green-50',
    'from-orange-50',
    'from-slate-50',
    'from-blue-500',
    'from-purple-500',
    'from-amber-500',
    'from-orange-500',
    'from-slate-600',
    // Gradient to colors
    'to-indigo-100',
    'to-blue-100',
    'to-emerald-100',
    'to-purple-100',
    'to-amber-100',
    'to-red-100',
    'to-green-100',
    'to-orange-100',
    'to-slate-100',
    'to-blue-600',
    'to-purple-600',
    'to-orange-500',
    'to-slate-700',
    // Border colors
    'border-indigo-200',
    'border-blue-200',
    'border-emerald-200',
    'border-purple-200',
    'border-amber-200',
    'border-red-200',
    'border-green-200',
    'border-orange-200',
    'border-slate-200',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
      },
    },
  },
  plugins: [
    require('flowbite/plugin')
  ],
}

